Update spec for tkgs cluster corresponding to changes in API
vmware/terraform-provider-tanzu-mission-control pull request #112
Opened 2023-01-06 07:17 UTC by Vasundharashukla

Signed-off-by: Vasundhara Shukla <vasundharas@vmware.com>

1. **What this PR does / why we need it**:
Add new spec attributes for TKGs workload cluster.

2. **Additional information**
Also added changes to example, resource templates and documentation.

4. **Special notes for your reviewer**

2023-01-11 09:26 UTC, shreyassreenivas approved these changes

2023-01-11 09:26 UTC, shreyassreenivas commented
Ensure these changes are tested and are working as expected

2023-01-11 09:31 UTC, shreyassreenivas commented
Acceptance is pending

2023-02-09 08:25 UTC, shobha2626 requested changes

2023-02-09 08:25 UTC, shobha2626 commented on internal/resources/cluster/tkgservicevsphere/topology_flatten_test.go
> +								FailureDomain: "",
Let's have the value populated in at least some UT cases

2023-02-09 08:25 UTC, shobha2626 commented on internal/resources/cluster/tkgservicevsphere/resource_tkg_service_vsphere.go
> +			},
We can't can UT's for these new parameters?

2023-02-09 17:46 UTC, ishangupta-ds requested changes
LGTM.

- Please add any required references to TMC documentation for this advanced config.
- Please update the unit tests and acceptance tests.

2023-02-13 10:18 UTC, ishangupta-ds approved these changes

2023-02-13 10:40 UTC, shreyassreenivas approved these changes

2023-02-13 18:17 UTC, shobha2626 approved these changes

2023-02-13 18:23 UTC, merged