Add models, clients and schema for Git repository and Kustomization resource
vmware/terraform-provider-tanzu-mission-control pull request #133
Opened 2023-03-07 06:21 UTC by ishangupta-ds

**What this PR does / why we need it**:

Add models, clients and schema for Git repository and Kustomization resource

2023-03-07 12:51 UTC, Vasundharashukla commented
@ishangupta-ds can we break the PR in 3 commits- models, clients and schema for better clarity and easy review?

2023-03-07 12:53 UTC, ishangupta-ds commented
> @ishangupta-ds can we break the PR in 3 commits- models, clients and schema for better clarity and easy review?

Sure

2023-03-14 11:50 UTC, Vasundharashukla commented on internal/models/policy/recipe/quota/custom.go
> +// # The input schema for namespace quota policy custom recipe version v1
nit: this is needed?

2023-03-14 12:03 UTC, Vasundharashukla requested changes

2023-03-24 11:02 UTC, ishangupta-ds commented
Closing due to corrupted commit history.

Addressed all the review comments here and raised another PR. Closing in favour of https://github.com/vmware/terraform-provider-tanzu-mission-control/pull/144

2023-03-24 11:02 UTC, closed without merging