Add models and clients for package install resource
vmware/terraform-provider-tanzu-mission-control pull request #213
Opened 2023-07-27 12:54 UTC by Shubbhang351

1. **What this PR does / why we need it**:

Add models and clients for package install resource

2023-07-31 17:28 UTC, shobha2626 requested changes

2023-07-31 17:28 UTC, shobha2626 commented on internal/resources/tanzupackageinstall/constant.go
> +	NamespaceKey   = "namespace_name"
namespace is good enough?

2023-08-07 06:54 UTC, shobha2626 approved these changes

2023-08-23 11:13 UTC, Shubbhang351 commented on internal/client/tanzupackageinstall/package_install.go
> +	InstallResourceServiceUpdate(request *packageinstall.VmwareTanzuManageV1alpha1ClusterNamespaceTanzupackageInstallCreateInstallRequest) (*packageinstall.VmwareTanzuManageV1alpha1ClusterNamespaceTanzu
updated PTAL

2023-08-29 06:23 UTC, merged