Merging feature branch for Package Deployment service to Main
vmware/terraform-provider-tanzu-mission-control pull request #253
Opened 2023-09-04 09:14 UTC by Shubbhang351

1. **What this PR does / why we need it**:

Merging feature branch for Package Deployment service to Main

2023-09-04 12:42 UTC, ramya-bangera commented on internal/resources/tanzupackageinstall/package_install_resource_test.go
> +package tanzupackageinstall
@Shubbhang351 - Shobha recently added the build tags to acceptance tests as part adding automation jobs of TMC terraform. Its daily simple task, can you work with Shobha to include build tags for these new resources as part of this change?

2023-09-05 07:10 UTC, ramya-bangera commented
Overall LGTM

2023-09-05 07:14 UTC, ramya-bangera submitted a review, later dismissed

2023-09-05 13:01 UTC, ishangupta-ds requested changes

2023-09-05 15:21 UTC, Shubbhang351 commented on internal/resources/package/package_mock_test.go
> +// nolint: unparam
updated

2023-09-05 15:21 UTC, Shubbhang351 commented on internal/resources/packages/packages_mock_test.go
> +// nolint: unparam
updated

2023-09-05 15:21 UTC, Shubbhang351 commented on examples/data-sources/package/data-source.tf
> +      cluster_name            = "testcluster" # Required
updatd

2023-09-06 06:54 UTC, ishangupta-ds commented on internal/models/package/cluster/package_spec.go
> +	// TODO: Determine how to detect ContentType and ContentEncoding of 'Raw' data.
Can you remove this TODO then or maybe make it a normal comment?

2023-09-06 06:59 UTC, Shubbhang351 commented on internal/models/package/cluster/package_spec.go
> +	// TODO: Determine how to detect ContentType and ContentEncoding of 'Raw' data.
updated PTAL

2023-09-06 06:59 UTC, ishangupta-ds approved these changes

2023-09-06 07:47 UTC, ramya-bangera approved these changes

2023-09-06 07:48 UTC, merged