Feat/secret
vmware/terraform-provider-tanzu-mission-control pull request #254
Opened 2023-09-04 10:00 UTC by Shubbhang351

1. **What this PR does / why we need it**:

2. **Which issue(s) this PR fixes**

        (optional, in `fixes #<issue number>` format, will close the issue(s) when PR gets merged):

        Fixes #

3. **Additional information**

4. **Special notes for your reviewer**

2023-09-05 07:12 UTC, ramya-bangera commented
@Shubbhang351 - I do not see the build tags changes added to this PR, am I missing something?

2023-09-05 12:56 UTC, ishangupta-ds requested changes

2023-09-05 16:01 UTC, Shubbhang351 commented on internal/resources/kubernetessecret/spec/spec.go
> +//nolint:all
updated PTAL

2023-09-05 16:01 UTC, Shubbhang351 commented on internal/resources/kubernetessecret/scope/scope.go
> +	// nolint: all
updated PTAL

2023-09-05 16:01 UTC, Shubbhang351 commented on internal/resources/kubernetessecret/resource_secret_mock_test.go
> +// nolint: ineffassign,staticcheck
updated PTAL

2023-09-05 16:01 UTC, Shubbhang351 commented on internal/resources/kubernetessecret/constants.go
> +//nolint:all
updated PTAL

2023-09-05 16:01 UTC, Shubbhang351 commented on internal/models/kubernetessecret/cluster/secret_spec.go
> +//nolint:all
updated PTAL

2023-09-06 06:56 UTC, ishangupta-ds approved these changes

2023-09-06 07:01 UTC, ishangupta-ds commented
@Shubbhang351 Before merging please ensure the commits are proper - I see 16 commits and the commit messages are not intuitive https://github.com/vmware/terraform-provider-tanzu-mission-control/pull/254/commits

2023-09-06 07:29 UTC, ishangupta-ds submitted a review, later dismissed

2023-09-06 07:45 UTC, ramya-bangera submitted a review, later dismissed

2023-09-06 08:37 UTC, ramya-bangera approved these changes

2023-09-06 09:25 UTC, ishangupta-ds approved these changes

2023-09-06 09:46 UTC, merged