Change terraform file style from imperative to declarative.
vmware/terraform-provider-tanzu-mission-control pull request #487
Opened 2024-12-31 21:32 UTC by stevewallone

### Summary

The terraform files use an imperative style, i.e. create_tkg_cluster. The convention is to use a declarative style that doesn't imply an actions, i.e. tkg_cluster.

### Type

- [ ] This is a bug fix.
- [ ] This is an enhancement or feature.
- [X ] This is a code style/formatting update.
- [ ] This is a documentation update.
- [ ] This is a refactoring update.
- [ ] This is a chore update
- [ ] This is something else.
      Please describe:

### Breaking Changes?

- [ ] Yes, there are breaking changes.
- [ X] No, there are no breaking changes.

### Test and Documentation

- [ ] Tests have been completed.
- [ ] Documentation has been added or updated.

### Issue References

Resolves #482 
### Additional Information

2025-01-13 21:33 UTC, stevewallone commented
I believe the commit message is good to go. Please let me know if there's anything else I need to do.

2025-01-13 22:55 UTC, tenthirtyam commented
The sign off needs to be on its own line.

2025-01-14 16:31 UTC, tenthirtyam commented
> The sign off needs to be on its own line.

@stevewallone - I've resolved the sign-off for you in [fa3e22a](https://github.com/vmware/terraform-provider-tanzu-mission-control/commit/fa3e22ab0e5f3566eb0e4b1860a9bf54adb1a351).

2025-01-14 16:39 UTC, tenthirtyam requested changes
All instances of the changes to `create_duration` to `duration` for the `hashicorp/time` provider need to be reverted.

The argument is [`create_duration`](https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep#create_duration-1).

2025-01-16 19:11 UTC, stevewallone commented
Closing PR. Will create another one that is clean.

2025-01-16 19:11 UTC, closed without merging