Vasundharas/documentation iam policy
vmware/terraform-provider-tanzu-mission-control pull request #61
Opened 2022-09-06 10:24 UTC by Vasundharashukla

1. **What this PR does / why we need it**: Documentation, use-cases, resource templates for IAM policy. Minor indentation fixes for security policy resource.

2. **Which issue(s) this PR fixes**

        (optional, in `fixes #<issue number>` format, will close the issue(s) when PR gets merged):

        Fixes #

3. **Additional information**

4. **Special notes for your reviewer**
Please review the content in iam_policy.md in docs directory.

2022-09-06 12:06 UTC, shreyassreenivas approved these changes

2022-09-06 20:09 UTC, ishangupta-ds requested changes

2022-09-06 20:09 UTC, ishangupta-ds commented on docs/resources/iam_policy.md
> +The `tanzu-mission-control_iam_policy` resource enables you to add, update and delete role bindings to a particular scope for management through Tanzu Mission Control.
management -> identity and access management

2022-09-06 20:09 UTC, ishangupta-ds commented on docs/resources/iam_policy.md
> +- **object groups** - `cluster_group` block under `scope` sub-resource
Can we only keep 3 levels and specify each of the allowed blocks under a particular level in the form of a list?

2022-09-07 13:11 UTC, ishangupta-ds requested changes

2022-09-07 13:11 UTC, ishangupta-ds commented on docs/resources/iam_policy.md
> +In the Tanzu Mission Control resource hierarchy, there are five levels at which you can specify IAM policy resources:
three levels

2022-09-07 13:11 UTC, ishangupta-ds commented on docs/resources/iam_policy.md
> +- **object groups** - `cluster_group` and `workspace` block under `scope` sub-resource
and -> or

2022-09-07 13:11 UTC, ishangupta-ds commented on docs/resources/iam_policy.md
> +- **Kubernetes objects** - `cluster` and `namespace` block under `scope` sub-resource
and -> or

2022-09-07 15:47 UTC, ishangupta-ds approved these changes

2022-09-08 11:19 UTC, merged