Add CRUD support for custom policy resource
vmware/terraform-provider-tanzu-mission-control pull request #82
Opened 2022-11-02 07:49 UTC by Vasundharashukla

1. **What this PR does / why we need it**:
Support functions of Create, Update, Read and Delete to provision custom policies.

3. **Additional information**

2022-11-02 10:37 UTC, ishangupta-ds requested changes

2022-11-02 10:37 UTC, ishangupta-ds commented on internal/resources/policy/type/custom/resource_custom_policy.go
> +	}
Please try to reuse these error formats across security and custom policies by declaring them at the policy level.

2022-11-02 10:37 UTC, ishangupta-ds commented on internal/resources/policy/type/custom/resource_custom_policy.go
> +func retrieveCustomPolicyUIDMetaAndSpecFromServer(config authctx.TanzuContext, scopedFullnameData *policy.ScopedFullname, d *schema.ResourceData, customPolicyName string) (string, *objectmetamodel.Vm
Reuse this function across security and custom policies.

2022-11-02 10:37 UTC, ishangupta-ds commented on internal/resources/policy/type/custom/resource_custom_policy.go
> +func resourceCustomPolicyInPlaceUpdate(ctx context.Context, d *schema.ResourceData, m interface{}) (diags diag.Diagnostics) {
Reuse this function across security and custom policies.

2022-11-09 12:23 UTC, ishangupta-ds approved these changes
LGTM.

2022-11-23 10:00 UTC, shreyassreenivas approved these changes

2022-11-23 11:10 UTC, merged